export const maxLengths = {
  CITY_MAX_LENGTH: 100,
  COMPLEMENT_MAX_LENGTH: 100,
  COUNTRY_MAX_LENGTH: 100,
  EMAIL_MAX_LENGTH: 255,
  NAME_MAX_LENGTH: 255,
  NUMBER_MAX_LENGTH: 6,
  PUBLIC_PLACE_MAX_LENGTH: 100,
  STATE_MAX_LENGTH: 100,
}
