const CITY_MAX_LENGTH = 100
const COMPLEMENT_MAX_LENGTH = 100
const COUNTRY_MAX_LENGTH = 100
const EMAIL_MAX_LENGTH = 255
const NAME_MAX_LENGTH = 255
const NUMBER_MAX_LENGTH = 6
const PUBLIC_PLACE_MAX_LENGTH = 100
const STATE_MAX_LENGTH = 100

export {
  CITY_MAX_LENGTH,
  COMPLEMENT_MAX_LENGTH,
  COUNTRY_MAX_LENGTH,
  EMAIL_MAX_LENGTH,
  NAME_MAX_LENGTH,
  NUMBER_MAX_LENGTH,
  PUBLIC_PLACE_MAX_LENGTH,
  STATE_MAX_LENGTH,
}
